spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: jdbc:mysql://localhost/web-app?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 12344321Qmnio
